# Parsers: cleaners, validators and judges

Language models answer questionnaires in free text. The `rupsycho.parsers` package turns
such text into data with three kinds of [LangChain output parsers](https://python.langchain.com/docs/concepts/output_parsers/):

| Kind | Question it answers | Rule-based | Model-based |
| --- | --- | --- | --- |
| **Cleaner** | What is the actual answer text? | `BasicCleaner`, `RegexExtractorCleaner`, `PromptRemovalCleaner` | |
| **Validator** | Is this an answer at all, or a refusal / "As an AI ..."? | `ApologiesValidatorParser`, `BeingAiValidatorParser`, `RefusalValidatorParser`, `ValidatorParser` | `ModelBasedValidator` |
| **Judge** | Which answer option does the text mean? | `MultipleChoiceJudge`, `DemographicsJudge` | `ModelBasedAnswerJudge` |

Every parser has `parse(text)` and, being a LangChain `Runnable`, `invoke`, `batch` and
the `|` operator. They can be used on their own (this notebook), as the output parser of
an experiment (`experiment.set_parser(...)`) or in the
[`PostprocessingPipeline`](Postprocessing.ipynb).

**Requirements.** The rule-based parsers need only the core package and run offline.
The model-based ones need the `huggingface` extra
(`pip install "rupsycho[huggingface] @ git+https://github.com/julianschelb/rupsycho.git"`)
and download a classifier of a few hundred MB from the Hugging Face Hub; their cells are
marked at the end of this notebook and have no stored output.

## Cleaners

A cleaner removes noise from the raw answer. `BasicCleaner` replaces line breaks, maps
typographic quotes to plain ASCII, strips other non-ASCII characters (emoji, ...) and
squeezes whitespace.

In [1]:
import pandas as pd

from rupsycho.parsers.cleaners import BasicCleaner, PromptRemovalCleaner, RegexExtractorCleaner

raw_output = "Hello, world!\nThis is a test text with some emojis \N{SMILING FACE WITH SMILING EYES} and line breaks.\n"
BasicCleaner().parse(raw_output)

'Hello, world! This is a test text with some emojis and line breaks.'

`RegexExtractorCleaner` extracts the first capture group of a pattern, e.g. the answer from
the `{answer: "..."}` format that the demo prompt asks the model for. If the pattern does not
match, the text is returned unchanged, so it is safe to apply to every answer.

In [2]:
extractor = RegexExtractorCleaner(pattern=r'answer\s*:\s*"([^"]+)"')

print(extractor.parse('{answer: "4. Agree a little"}'))
print(extractor.parse("I think 4."))

4. Agree a little
I think 4.

`PromptRemovalCleaner` cuts off an echoed prompt: some models repeat the question before
they answer. The result is lower-cased.

In [3]:
prompt = "Question: Does a thorough job\nAnswer Options: 1. Disagree strongly, 2. Disagree a little\nAnswer:"
echoed = prompt + " 2. Disagree a little"

PromptRemovalCleaner(prompt=prompt, similarity_threshold=0.7, fast=False).parse(echoed)

'2. disagree a little'

## Validators

A validator decides whether an answer is usable. The rule-based validators look at how the
answer *starts* (plus a few catch-all phrases); the prefix lists come from the
[llm-values-pct](https://github.com/paul-rottger/llm-values-pct) repository.
`ValidatorParser` combines the apology, "being an AI" and refusal checks.

In [4]:
from rupsycho.parsers.validators import (
    ApologiesValidatorParser,
    BeingAiValidatorParser,
    RefusalValidatorParser,
    ValidatorParser,
)

example_texts = {
    "plain": "I think I would choose option 1 because it seems the best.",
    "apologies": "I apologize for the inconvenience.",
    "being_ai": "As an AI, I do not have personal opinions.",
    "refusal": "I cannot provide that information.",
    "combined": "I apologize for any confusion, but as an AI, I cannot provide that information.",
}
validators = {
    "apologies": ApologiesValidatorParser(),
    "being_ai": BeingAiValidatorParser(),
    "refusal": RefusalValidatorParser(),
    "combined": ValidatorParser(),
}


def verdicts(validator):
    return {key: validator.parse(text)["validation_status"] for key, text in example_texts.items()}


pd.DataFrame({name: verdicts(validator) for name, validator in validators.items()})

          apologies being_ai  refusal combined
plain         valid    valid    valid    valid
apologies   invalid    valid    valid  invalid
being_ai      valid  invalid  invalid  invalid
refusal       valid    valid  invalid  invalid
combined    invalid    valid    valid  invalid

Each validator returns the unmodified text, a `validation_status` (`"valid"` or
`"invalid"`) and the individual findings under `details`. Note that the last example
starts with an apology, so only the apology check fires.

In [5]:
ValidatorParser().parse(example_texts["combined"])

{'text': 'I apologize for any confusion, but as an AI, I cannot provide that information.',
 'validation_status': 'invalid',
 'details': {'apologies': True, 'being_ai': False, 'refusal': False}}

## Judges

A judge decides which answer option a text corresponds to. `MultipleChoiceJudge` splits
every option into its enumeration (`1`, `A`, ...) and its text, and counts how often both
occur in the answer. The option with the most hits wins; `not present` means that no option
was recognised and `inconclusive` that several options fit equally well.

In [6]:
from rupsycho.parsers.judges import MultipleChoiceJudge

options = [
    "1. Disagree strongly",
    "2. Disagree a little",
    "3. Neither agree nor disagree",
    "4. Agree a little",
    "5. Agree strongly",
]
judge = MultipleChoiceJudge(possible_answers=options)

answers = [
    "4",
    "Agree a little",
    'I would say "2. Disagree a little".',
    "Somewhere between 2 and 3.",
    "It depends on the situation.",
]
pd.DataFrame({"answer": answers, "decision": [judge.invoke(answer) for answer in answers]})

                                answer              decision
0                                    4     4. Agree a little
1                       Agree a little     4. Agree a little
2  I would say "2. Disagree a little".  2. Disagree a little
3           Somewhere between 2 and 3.          inconclusive
4         It depends on the situation.           not present

Matching ignores case unless you pass `ignore_case=False`. The pipeline hands the answer
options of each question to the judge (`judge.parse(text, possible_answers=...)`), which
overrides the list given to the constructor; questions can therefore have different
options.

In [7]:
strict = MultipleChoiceJudge(possible_answers=options, ignore_case=False)
print("ignore_case=True :", judge.parse("agree a little"))
print("ignore_case=False:", strict.parse("agree a little"))
print("own options      :", judge.parse("B", possible_answers=["A. yes", "B. no"]))

ignore_case=True : 4. Agree a little
ignore_case=False: not present
own options      : B. no

`DemographicsJudge` reads demographic statements instead (used when the "questionnaire"
asks the model for its gender or age). The question type is given by the first possible
answer, `"gender"` or `"age"`.

In [8]:
from rupsycho.parsers.judges import DemographicsJudge

gender = DemographicsJudge()
gender.parse("I am a 25 year old woman.", possible_answers=["gender"])

'female'

## Parsers are runnables

Parsers compose with `|` and work on batches, like every LangChain runnable:

In [9]:
chain = BasicCleaner() | ValidatorParser()
[result["validation_status"] for result in chain.batch(["4", "As an AI, I have no opinion.\n"])]

['valid', 'invalid']

As the **output parser of an experiment** (`experiment.set_parser`) a cleaner is applied
to every answer before it is stored. Here a built-in fake model replies with a messy
string:

In [10]:
import warnings

from langchain_core.language_models.fake import FakeListLLM

import rupsycho as rup

warnings.filterwarnings("ignore", message="Models of type FakeListLLM")  # it has no seed

experiment = rup.load_example_experiment("bfi", models={})
reply = "Hmm...\n\n4. Agree a little \N{SMILING FACE WITH SMILING EYES}"
experiment.add_model(FakeListLLM(responses=[reply]), identifier="fake")
experiment.set_parser(BasicCleaner())
experiment.run(show_progress=False)
experiment.get_answers_as_dataframe()["Answer"].unique()

array(['Hmm... 4. Agree a little'], dtype=object)

## Model-based parsers (download required)

The rule-based parsers are fast and transparent, but they look at surface forms only.
`ModelBasedAnswerJudge` and `ModelBasedValidator` use fine-tuned classifiers from the
Hugging Face Hub instead. They need `pip install "rupsycho[huggingface]"` and download the
classifier on first use, so the following cells were **not executed** for this notebook
(they carry the `skip-execution` tag).

The judge scores every answer option against the answer with a RoBERTa classifier and
returns `inconclusive` when the probabilities are too evenly spread (entropy above
`entropy_threshold`).

In [ ]:
from rupsycho.parsers.judges import ModelBasedAnswerJudge

possible_answers = ["1. never or seldom", "2.", "3. sometimes", "4.", "5. always"]
model_judge = ModelBasedAnswerJudge(
    possible_answers=possible_answers,
    model_name="julian-schelb/rup-answer-option-likert-scale",
    device="cpu",
)
sure = "I always do my best to be honest."
torn = "I always do my best to be honest. But sometimes I fail. So I would say either 3 or 5."
print(model_judge.parse(sure))  # 5. always
print(model_judge.parse(torn))  # inconclusive

In [ ]:
from rupsycho.parsers.validators import ModelBasedValidator

model_validator = ModelBasedValidator("protectai/distilroberta-base-rejection-v1", device="cpu")
model_validator.parse("Sorry, but I can't assist with that.")
# {'text': ..., 'validation_status': 'invalid', 'confidence_score': 0.99...}