# Post-processing: from free text to answer options

The answers of a language model are free text. The `PostprocessingPipeline` reads the CSV
files written by `CSVCallback` and adds, for every answer,

* `cleaned_answer`: the answer after the **cleaner**,
* `validation_status` and `valid`: the verdict of the **validator** (refusals and
  "As an AI ..." are not answers),
* `decision`: the answer option chosen by the **judge** (`not present` and
  `inconclusive` are possible, too).

**Requirements.** Only the core package; the rule-based parsers used here run offline.
The input is the sample result file `data/output/bfi_demo_config_output.csv`. It was
created offline by `make_sample_outputs.py`, which runs the demo configuration with a
*scripted stand-in model* (model id `scripted`) whose hand-written replies imitate the
typical problems of free-text answers. To process your own results, run an experiment with a
`CSVCallback` (see [Callbacks.ipynb](Callbacks.ipynb)) and point `results_file_patterns`
to that file. The model-based parsers are in [Parsers.ipynb](Parsers.ipynb).

## Inputs

The pipeline needs the experiment configuration (it provides the answer options of each
question) and the result files; a list of paths or glob patterns is accepted.

In [1]:
from pathlib import Path

import pandas as pd

DATA = Path("data")
if not DATA.exists():  # the notebook was opened from the repository root
    DATA = Path("examples") / DATA

config_file_path = DATA / "bfi_demo_config.json"
results_file_patterns = [str(DATA / "output" / "bfi_demo_config_output.csv")]
output_path = DATA / "output" / "bfi_demo_config_output_processed.csv"

raw = pd.read_csv(results_file_patterns[0])
print(list(raw.columns))
raw[["instruction_item_id", "profile_id", "answer"]]

['experiment_name', 'instruction_item_id', 'instruction_item', 'model_id', 'profile_id', 'random_seed', 'time', 'answer']

,instruction_item_id,profile_id,answer
0,0,Optimistic Persona,"{answer: ""4. Agree a little""}"
1,0,Conservative Persona,3
2,1,Optimistic Persona,"I would say ""2. Disagree a little""."
3,1,Conservative Persona,"As an AI, I do not have personal opinions on t..."
4,2,Optimistic Persona,5. Agree strongly\n\nI always make sure to do ...
5,2,Conservative Persona,It depends on the situation.
6,3,Optimistic Persona,Disagree strongly.
7,3,Conservative Persona,Somewhere between 2 and 3.
8,4,Optimistic Persona,"{answer: ""4. Agree a little""}"
9,4,Conservative Persona,3

## Define the parsers

**Cleaner.** The prompt of the demo asks for the format `{answer: "answer option"}`.
`RegexExtractorCleaner` extracts the option from it and leaves every other text unchanged.

In [2]:
from rupsycho.parsers.cleaners import RegexExtractorCleaner

cleaner = RegexExtractorCleaner(pattern=r'answer\s*:\s*"([^"]+)"')
print(cleaner.invoke('{answer: "4. Agree a little"}'))
print(cleaner.invoke("3"))

4. Agree a little
3

**Validator.** `ValidatorParser` marks apologies, "As an AI ..." and refusals as invalid.

In [3]:
from rupsycho.parsers.validators import ValidatorParser

validator = ValidatorParser()
print(validator.invoke("I always do my best to be honest.")["validation_status"])
print(validator.invoke("I am sorry, I always do my best to be honest.")["validation_status"])
validator.invoke("As an AI, I do not have personal opinions on this.")

valid
invalid

{'text': 'As an AI, I do not have personal opinions on this.',
 'validation_status': 'invalid',
 'details': {'apologies': False, 'being_ai': True, 'refusal': True}}

**Judge.** `MultipleChoiceJudge` picks the answer option that the text mentions most. The
pipeline passes the options of each question to it; the list given here is the fallback.

In [4]:
from rupsycho.parsers.judges import MultipleChoiceJudge

judge = MultipleChoiceJudge(
    possible_answers=[
        "1. Disagree strongly",
        "2. Disagree a little",
        "3. Neither agree nor disagree",
        "4. Agree a little",
        "5. Agree strongly",
    ]
)
for text in ["Agree a little", "Somewhere between 2 and 3.", "It depends on the situation."]:
    print(f"{text!r:35} -> {judge.invoke(text)}")

'Agree a little'                    -> 4. Agree a little
'Somewhere between 2 and 3.'        -> inconclusive
'It depends on the situation.'      -> not present

## Run the pipeline

`show_progress=False` hides the progress bars; `errors="coerce"` would log rows that a
parser cannot handle and leave their cells empty instead of stopping (the default,
`errors="raise"`, fails early). The processed table is returned and written to
`output_path`.

In [5]:
from rupsycho.postprocessing import PostprocessingPipeline

pipeline = PostprocessingPipeline(
    config_file_path,
    results_file_patterns,
    cleaner=cleaner,
    validator=validator,
    judge=judge,
    output_path=output_path,
    show_progress=False,
)
processed = pipeline.run()
print(list(processed.columns))

['experiment_name', 'instruction_item_id', 'instruction_item', 'model_id', 'profile_id', 'random_seed', 'time', 'answer', 'cleaned_answer', 'validation_status', 'valid', 'decision']

In [6]:
processed[["instruction_item_id", "profile_id", "cleaned_answer", "valid", "decision"]]

,instruction_item_id,profile_id,cleaned_answer,valid,decision
0,0,Optimistic Persona,4. Agree a little,True,4. Agree a little
1,0,Conservative Persona,3,True,3. Neither agree nor disagree
2,1,Optimistic Persona,"I would say ""2. Disagree a little"".",True,2. Disagree a little
3,1,Conservative Persona,"As an AI, I do not have personal opinions on t...",False,not present
4,2,Optimistic Persona,5. Agree strongly\n\nI always make sure to do ...,True,5. Agree strongly
5,2,Conservative Persona,It depends on the situation.,True,not present
6,3,Optimistic Persona,Disagree strongly.,True,1. Disagree strongly
7,3,Conservative Persona,Somewhere between 2 and 3.,True,inconclusive
8,4,Optimistic Persona,4. Agree a little,True,4. Agree a little
9,4,Conservative Persona,3,True,3. Neither agree nor disagree

Read the table as follows:

* The first answer was given in the requested `{answer: ...}` format, the cleaner
  extracted the option and the judge confirmed it.
* The refusal of the second persona is flagged by the validator (`valid` is `False`). The
  judge still returns `not present` for it; refusals must be excluded from the scores
  whatever the judge says.
* `It depends on the situation.` is a valid answer text that names no option
  (`not present`), and `Somewhere between 2 and 3.` names two (`inconclusive`).

Usable answers are the valid ones with a real option as the decision:

In [7]:
undecided = ["not present", "inconclusive"]
usable = processed[processed["valid"] & ~processed["decision"].isin(undecided)]
print(f"{len(usable)} of {len(processed)} answers are usable")
usable[["instruction_item_id", "profile_id", "decision"]]

7 of 10 answers are usable

   instruction_item_id            profile_id                       decision
0                    0    Optimistic Persona              4. Agree a little
1                    0  Conservative Persona  3. Neither agree nor disagree
2                    1    Optimistic Persona           2. Disagree a little
4                    2    Optimistic Persona              5. Agree strongly
6                    3    Optimistic Persona           1. Disagree strongly
8                    4    Optimistic Persona              4. Agree a little
9                    4  Conservative Persona  3. Neither agree nor disagree

The weight of each decided option is the score of the answer (reversed items flip the
scale): see the last sections of [quickstart.ipynb](quickstart.ipynb). The same pipeline
is available from the command line (run from the `examples/` folder):

```bash
rupsycho postprocess data/bfi_demo_config.json data/output/bfi_demo_config_output.csv \
  -o processed.csv --pattern 'answer\s*:\s*"([^"]+)"'
```